version: 2.1
orbs:
    sonarcloud: sonarsource/sonarcloud@1.0.1
jobs:
    build:
        docker:
            - image: denisgoncharenko/ubuntu-with-dotnet-packages
        steps:
            - checkout
            - run:
                name: Restore
                command: dotnet restore --no-cache
            - run:
                name: Build
                command: dotnet build --configuration Release --no-restore
            - sonarcloud/scan
            - run:
                name: Test
                command: dotnet test
workflows:
    version: 2
    workflow:
        jobs:
        - build:
            filters:
                branches:
                    only: master